/*
  Warnings:

  - You are about to drop the column `id` on the `Tournament` table. All the data in the column will be lost.
  - You are about to drop the column `name` on the `Tournament` table. All the data in the column will be lost.
  - Added the required column `currentStage` to the `Tournament` table without a default value. This is not possible if the table is not empty.
  - Added the required column `gamemode` to the `Tournament` table without a default value. This is not possible if the table is not empty.
  - Added the required column `tourDesc` to the `Tournament` table without a default value. This is not possible if the table is not empty.
  - Added the required column `tourName` to the `Tournament` table without a default value. This is not possible if the table is not empty.

*/
-- CreateEnum
CREATE TYPE "Gamemode" AS ENUM ('STANDARD', 'TAIKO', 'CTB', 'MANIA');

-- CreateEnum
CREATE TYPE "MatchStatus" AS ENUM ('NOT_STARTED', 'IN_PROGRESS', 'PAUSED', 'ENDED');

-- CreateEnum
CREATE TYPE "Visibility" AS ENUM ('PUBLIC', 'PRIVATE');

-- CreateTable
CREATE TABLE "Stage" (
    "tournamentId" INT8 NOT NULL,
    "stageNo" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "stageName" STRING NOT NULL,
    "isBracket" BOOL NOT NULL,

    CONSTRAINT "Stage_pkey" PRIMARY KEY ("tournamentId","stageNo")
);

-- CreateTable
CREATE TABLE "Match" (
    "tournamentId" INT8 NOT NULL,
    "stageNo" INT4 NOT NULL,
    "matchId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "team1Score" INT4 NOT NULL,
    "team2Score" INT4 NOT NULL,
    "team1Id" STRING NOT NULL,
    "team2Id" STRING NOT NULL,
    "matchStatus" "MatchStatus" NOT NULL,
    "matchDateTime" TIMESTAMP(3) NOT NULL,
    "referee" STRING,

    CONSTRAINT "Match_pkey" PRIMARY KEY ("tournamentId","matchId")
);

-- CreateTable
CREATE TABLE "Mappool" (
    "tournamentId" INT8 NOT NULL,
    "stageNo" INT4 NOT NULL,
    "mapId" INT4 NOT NULL,

    CONSTRAINT "Mappool_pkey" PRIMARY KEY ("tournamentId","stageNo","mapId")
);

-- CreateTable
CREATE TABLE "Registrations" (
    "regId" INT8 NOT NULL DEFAULT unique_rowid(),
    "tournamentId" INT8 NOT NULL,
    "userId" STRING NOT NULL,

    CONSTRAINT "Registrations_pkey" PRIMARY KEY ("regId")
);

-- RedefineTables
CREATE TABLE "_prisma_new_Tournament" (
    "tournamentId" INT8 NOT NULL DEFAULT unique_rowid(),
    "tourName" STRING NOT NULL,
    "tourDesc" STRING NOT NULL,
    "bannerUrl" STRING,
    "gamemode" "Gamemode" NOT NULL,
    "currentStage" INT4 NOT NULL,
    "visibility" "Visibility" NOT NULL DEFAULT 'PRIVATE',

    CONSTRAINT "Tournament_pkey" PRIMARY KEY ("tournamentId")
);
DROP TABLE "Tournament" CASCADE;
ALTER TABLE "_prisma_new_Tournament" RENAME TO "Tournament";

-- AddForeignKey
ALTER TABLE "Stage" ADD CONSTRAINT "Stage_tournamentId_fkey" FOREIGN KEY ("tournamentId") REFERENCES "Tournament"("tournamentId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Match" ADD CONSTRAINT "Match_tournamentId_stageNo_fkey" FOREIGN KEY ("tournamentId", "stageNo") REFERENCES "Stage"("tournamentId", "stageNo") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Mappool" ADD CONSTRAINT "Mappool_tournamentId_stageNo_fkey" FOREIGN KEY ("tournamentId", "stageNo") REFERENCES "Stage"("tournamentId", "stageNo") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Registrations" ADD CONSTRAINT "Registrations_tournamentId_fkey" FOREIGN KEY ("tournamentId") REFERENCES "Tournament"("tournamentId") ON DELETE RESTRICT ON UPDATE CASCADE;
